FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt install -y \
    bash \
    ca-certificates \
    coreutils \
    curl \
    git \
    git-lfs \
    gnupg \
    gzip \
    sudo \
    tar \
    unzip \
    wget

RUN echo "deb http://archive.neon.kde.org/user noble main" > \
 /etc/apt/sources.list.d/neon.list \
 && wget -qO - https://archive.neon.kde.org/public.key | apt-key add - \
 && apt-get update

RUN apt install -y \
    build-essential \
    clang \
    clang-format \
    clang-tidy \
    cmake \
    curl \
    file \
    fuse3 \
    git \
    kf6-kimageformat-plugins \
    lcov \
    libexiv2-dev \
    libgl-dev \
    libgtest-dev \
    libheif-dev \
    libheif-plugin-j2kdec \
    libheif-plugin-jpegdec \
    libheif-plugin-libde265 \
    libopencv-dev \
    libqt6core5compat6-dev \
    libqt6svg6-dev \
    libquazip1-qt6-dev \
    libraw-dev \
    libtiff-dev \
    ninja-build \
    qt6-base-dev \
    qt6-image-formats-plugins \
    qt6-l10n-tools \
    qt6-tools-dev \
    qt6-tools-dev-tools \
    rsync

COPY ./scripts/build-linuxdeploy.sh ./
RUN ./build-linuxdeploy.sh

RUN apt upgrade -y

RUN apt clean && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENTRYPOINT []
CMD []
USER root
